OCRS/OCRS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include('mysite.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/login/',auth_views.LoginView.as_view(),name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
]

OCRS/mysite/urls.py
from django.urls import path
from mysite import views

app_name='mysite'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('courses/',views.CourseListView.as_view(),name='courses'),
    path('courses/<int:pk>/',views.CourseDetailView.as_view(),name="course_detail"),
    path('accounts/profile/',views.IndexView.as_view()), # change this later
]

OCRS/mysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True,null=True)
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.teacher_name

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True,null=True)
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Course(models.Model):
    course_name = models.CharField(max_length=50)
    course_description = models.CharField(max_length=300)
    students = models.ManyToManyField(Student)
    teacher = models.ManyToManyField(Teacher)
    def __str__(self):
        return self.course_name

class Grade(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    grade = models.PositiveIntegerField()

OCRS/mysite/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from mysite.models import Course
# Create your views here.

class IndexView(TemplateView):
    template_name="mysite/index.html"

class CourseListView(ListView):
    model = Course

class CourseDetailView(DetailView):
    model = Course

class EnrollCourseView(TemplateView):
    pass

OCRS/mysite/templates/mysite/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>OCRS</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class='navbar-brand' href="{% url 'mysite:index' %}">OCRS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class='navbar-nav mr-auto'>
        <li class='nav-item active'> <a class='nav-link' href="{% url 'mysite:courses' %}">Courses</a></li>
      </ul>

      <ul class='navbar-nav ml-auto'>
        {% if user.is_authenticated %}
        <li class='nav-item active'> <a class='nav-link' href="#">Welcome {{ user.username }}</a></li>
        <li class='nav-item active'> <a class='nav-link' href="{% url 'logout' %}">LOGOUT</a></li>
        {% else %}
        <li class='nav-item'> <a class='nav-link' href="{% url 'login' %}">LOGIN</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>

  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

OCRS/mysite/templates/mysite/course_detail.html
{% extends "mysite/base.html"%}

{% block body_block %}
<div class="jumbotron">
  <h3>Course Name: {{object.course_name}}</h3><br>
  <h5>Course Description: {{object.course_description}}</h5><br>
  {% for teacher in object.teacher.all %}
  <h5>Teacher:</h5>
  <p>{{teacher.teacher_name}}</p>
  {% empty %}
  <p>NONE</p>
  {% endfor %}
  <h5>Students: </h5>
  <ul>
    {% for student in object.students.all %}
    <li>{{student.name}}</li>
    {% empty %}
    <p>NONE</p>
    {% endfor %}
  </ul>
</div>

{% endblock %}

OCRS/mysite/templates/mysite/course_enroll.html
{% extends "mysite/base.html" %}

OCRS/mysite/templates/mysite/course_list.html
{% extends "mysite/base.html" %}

{% block body_block %}
      {% for course in course_list %}
      <h1><a href="{{course.id}}">{{course.course_name}}</a><br></h1>
      {% empty %}
      <p>NO COURSES YET!!!</p>
      {% endfor %}


{% endblock %}

OCRS/mysite/templates/mysite/index.html
{% extends "mysite/base.html" %}

{%block body_block %}
<div class="jumbotron">
  <h1>Index Page</h1>
</div>
{% endblock %}